### ISSUE TITLE
How can I test the bot?

### ISSUE THREAD

**Issue by tylerlong** [pkvenu/developing-locally-with-Glip#1]
I have finished all the steps mentioned in README.

But I have no idea of where the bot is and how can I interact with it.

**Comment by pkvenu** [comment]
@tylerlong - I have added more screenshots on how to discover and add the bot. Please review and let me know if that solves the issue.

**Comment by tylerlong** [comment]
Thank you for the response. But I cannot find the bot user after login Glip.  sandbox environment.

**Comment by tylerlong** [comment]
It turns out that the bot user doesn't have a phone number associated and its email address is auto generated. So the only way to find the user is by name. And it also means that you can only add the user from the same company (no guest user).
